env:
  es6: true
  node: true

parserOptions:
  #ecmaVersion: 2015 (6)
  #ecmaVersion: 2016 (7) (node 6)
  #ecmaVersion: 2017 (8) (node 8)
  #ecmaVersion: 2018 (9) (node 10)
  #ecmaVersion: 2019 (10) (node 12)
  #ecmaVersion: 2020 (11) (node 14)
  ecmaVersion: 2020

plugins:
  - haraka

root: true

rules:
  semi-style: [error, last]
  prefer-template: "warn"
  no-unneeded-ternary: 1

extends: ["eslint:recommended", "plugin:haraka/recommended"]
