#!/usr/bin/env node

"use strict";

try {
    var reporter = require('nodeunit').reporters.default;
}
catch(e) {
    console.log("Error: " + e.message);
    console.log("");
    console.log("Cannot find nodeunit module.");
    console.log("Please run the following:");
    console.log("");
    console.log("    npm install");
    console.log("");
    process.exit();
}

process.chdir(__dirname);
reporter.run(['tests', 'tests/plugins']);
