#!/bin/sh

# Files using node:test
NODE_TEST_FILES="test/*.js test/outbound/*.js test/plugins/*.js test/plugins/auth/*.js test/plugins/queue/*.js"

if [ -n "$1" ]; then
    node --test "$1"
else
    # default, run 'em all
    node --test --test-concurrency=1 $NODE_TEST_FILES
fi
