; host to connect to
host=localhost
;
; port to connect to
port=2555
;
; uncomment to enable TLS to the backend SMTP server
;enable_tls=true
;
; for messages that have multiple RCPT, send a separate message for each RCPT
; when forwarding.
;one_message_per_rcpt=true
;
; uncomment to use smtp client authorization
;auth_type=plain
;auth_user=
;auth_pass=

; should outbound messages be delivered by smtp_forward?
; see #1472 and #2795
; enable_outbound=false

; Options here override the same option in tls.ini [main]
[tls]
; rejectUnauthorized=true
; minVersion=TLSv1.2
; ciphers=ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
; key=outbound_tls_key.pem
; cert=outbound_tls_cert.pem
; no_tls_hosts[]=10.0.0.5
; force_tls_hosts[]=mx.example.com
