name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: master

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  prettier:
    uses: haraka/.github/.github/workflows/prettier.yml@master
    with:
      branch: ${{ github.head_ref }}

  coverage:
    uses: haraka/.github/.github/workflows/coverage.yml@master
    secrets: inherit

  ubuntu:
    uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    uses: haraka/.github/.github/workflows/windows.yml@master

  macos:
    uses: haraka/.github/.github/workflows/macos.yml@master
