name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

env:
  CI: true

permissions:
  contents: read

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  prettier:
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    uses: haraka/.github/.github/workflows/prettier.yml@master
    permissions:
      contents: write
    secrets: inherit
    with:
      branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

  coverage:
    uses: haraka/.github/.github/workflows/coverage.yml@master
    secrets: inherit

  ubuntu:
    uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    uses: haraka/.github/.github/workflows/windows.yml@master

  macos:
    uses: haraka/.github/.github/workflows/macos.yml@master
