name: CI

on: [ pull_request, push ]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  test:
    needs: [ lint, get-lts ]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: ${{ fromJson(needs.get-lts.outputs.active) }}
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install bsdtar
      run: sudo apt-get update; sudo apt-get install -y libarchive-tools
    - run: npm install
    - run: npm run test

  # TODO: replace the above with this, after plugin/attachment is split
  # ubuntu:
  #   needs: [ lint ]
  #   uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    needs: [ lint ]
    uses: haraka/.github/.github/workflows/windows.yml@master

  get-lts:
     runs-on: ubuntu-latest
     steps:
       - id: get
         uses: msimerson/node-lts-versions@v1
     outputs:
       active: ${{ steps.get.outputs.active }}
       lts:    ${{ steps.get.outputs.lts }}
       min:    ${{ steps.get.outputs.min }}
