name: CI

on: [pull_request, push]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  ubuntu:
    needs: [ lint ]
    uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    needs: [lint]
    uses: haraka/.github/.github/workflows/windows.yml@master

  get-lts:
    runs-on: ubuntu-latest
    steps:
      - id: get
        uses: msimerson/node-lts-versions@v1
    outputs:
      active: ${{ steps.get.outputs.active }}
      maintenance: ${{ steps.get.outputs.maintenance }}
      lts: ${{ steps.get.outputs.lts }}
      current: ${{ steps.get.outputs.current }}
      min: ${{ steps.get.outputs.min }}
