name: publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  packages: write

env:
  CI: true

jobs:
  publish:
    uses: haraka/.github/.github/workflows/publish.yml@master
    secrets: inherit
