name: release

on:
  push:
    branches: [main, master]
    paths:
      - package.json

env:
  CI: true

jobs:
  release:
    uses: haraka/.github/.github/workflows/release.yml@master
    permissions:
      contents: write
    secrets: inherit

  publish:
    needs: release
    if: needs.release.outputs.changed == 'true'
    uses: haraka/.github/.github/workflows/publish.yml@master
    permissions:
      contents: read
      packages: write
      id-token: write
    secrets: inherit
